language: node_js
dist: trusty
sudo: required
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 7.4.0
  - nvm use 7.4.0
  - npm install -g yarn
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=0.18.1-1
  - yarn --version
script:
  - yarn run lint && yarn test
notifications:
  slack:
    secure: bDwO2uce5JAZvjrvWj4+/+yEXJAIK4O0RcgUWvZ2IMbi7Q9I89Mw40JmkLWL6x2gWZwxr8+FoLtErJA7RVrsfImjrX+NmMyAB7AydLdrBJtkLozNnuacnhcnBRyp1gGCa1ymxCEXGbgC6onAD3kiJJhggr70T+2lu3IuJYXENhc=
env:
  - CXX=g++-4.8 NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8
      - libgnome-keyring-dev
cache:
  yarn: true
